name: Build iOS app
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  build:
    name: Build and test
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Install Dependencies
      run:
        pod install --repo-update
      shell: bash
    - name: Run tests
      run: ./run_tests.sh

  build_with_signing:
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: >
          # create variables

          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12

          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision

          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db


          # import certificate and provisioning profile from secrets

          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o
          $CERTIFICATE_PATH

          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o
          $PP_PATH


          # create temporary keychain

          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH

          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH


          # import certificate to keychain

          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f
          pkcs12 -k $KEYCHAIN_PATH

          security list-keychain -d user -s $KEYCHAIN_PATH


          # apply provisioning profile

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles

          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
  
      - name: Install Dependencies
        run:
          pod install --repo-update
        shell: bash
      - name: build archive
        run: |
          xcodebuild -scheme "Devskiller" \
          -workspace Customers.xcworkspace \
          -archivePath $RUNNER_TEMP/devskiller.xcarchive \
          -sdk iphoneos \
          -configuration Debug \
          -destination generic/platform=iOS \
          clean archive
      - name: export ipa
        env:
          EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
        run: >
          EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist

          echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH

          xcodebuild -exportArchive -archivePath
          $RUNNER_TEMP/devskiller.xcarchive -exportOptionsPlist
          $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build
      - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ${{ runner.temp }}/build/devskiller.ipa
          retention-days: 3

